PointsDeFidelite/PointsDeFidelite/Controllers/RoleController.cs
using System;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PointsDeFidelite.Models;
using Microsoft.AspNet.Identity.EntityFramework;

namespace PointsDeFidelite.Controllers
{
    public class RoleController : Controller
    {
        private ApplicationDbContext context;
        // GET: Role
        public ActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {


                if (!isAdminUser())
                {
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

            var Roles = context.Roles.ToList();
            return View(Roles);
        }

        public Boolean isAdminUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                var user = User.Identity;
                ApplicationDbContext context = new ApplicationDbContext();
                var UserManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(context));
                var s = UserManager.GetRoles(user.GetUserId());
                if (s[0].ToString() == "Admin")
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            return false;
        }
    }
}

PointsDeFidelite/PointsDeFidelite/Views/Role/Index.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Add Role";
}

<table style="background-color : #FFFFFF; border: dashed 3px #6D7B8D; padding: 5px; width: 99%; table-layout:fixed;"  cellpadding="6"  cellspacing="6">
    <tr style="height: 30px; background-color: #336699; color: #FFFFFF; border: solid 1px #659EC7;">
        <td align="center"  colspan="2">
            <h2> Create User Roles</h2>
        </td>

    </tr>

    <tr>
        <td>
            <table id="tbrole"  style="width:100%; border:dotted 1px; background-color:gainsboro; padding-left:10px;">

                @foreach (var item in Model)
                {

                    <tr>
                        <td style="width:100%; border: dotted 1px;">
                            @item.Name
                        </td>
                    </tr>}
            </table>
        </td>
        <td align="right"  style="color:#FFFFFF;padding-right:10;">


            <h3>   @Html.ActionLink("Click to Create New Role", "Create", "Role") </h3>
        </td>
    </tr>
</table>