ContactManager/ContactManager/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ContactManager.Models
{
    public class Employee
    {
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string screen_name { get; set; }
        public int fixScore { get; set; }
        public int variableScore { get; set; }
        public List<Activity> activities { get; set; }
        public List<RewardUsed> rewards_used { get; set; }


    }
}

ContactManager/ContactManager/Models/Employees.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Newtonsoft.Json;

namespace ContactManager.Models
{
    public class Employees
    {
        [JsonProperty(PropertyName = "id")]
        public string id { get; }

        //[JsonProperty(PropertyName = "employees")]
        public List<Employee>employees { get; set; }
    }
}

ContactManager/ContactManager/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.Mvc;
using System.Web.Security;
using System.Net;
using System.Threading.Tasks;
using ContactManager.Models;
using Newtonsoft.Json;
using Microsoft.AspNet.Identity;
using System.IO;
using System.Text;
using System.Collections.Specialized;
using System.Net.Http;
using System.Windows.Forms;

namespace ContactManager.Controllers
{
    [Authorize(Roles = "Employee")]
    public class EmployeesController : Controller
    {
        [ActionName("Index")]
        public ActionResult Index()
        {
            using (var context = new ApplicationDbContext())
            {
                var username = User.Identity.Name;
                var user = context.Users.FirstOrDefault(p => p.UserName == username);
                if (user != null)
                {
                    WebRequest request = WebRequest.Create("https://fidelitefunctionapp.azurewebsites.net/api/GetTopTenEmployees");
                    request.Method = "POST";
                    request.ContentType = "application/json";

                    Stream dataStream = request.GetRequestStream();
                    WebResponse response = request.GetResponse();
                    dataStream = response.GetResponseStream();
                    StreamReader reader = new StreamReader(dataStream);
                    string responseFromServer = reader.ReadToEnd();
                    reader.Close();
                    dataStream.Close();
                    response.Close();

                    var first = responseFromServer.Replace("\"", "'");
                    var ranking = JsonConvert.DeserializeObject<List<Rank>>(first);


                    //var employees = DocumentDBRepository<Employees>.getEmployeesActivities();
                    //var e = new Employees();
                    ////will only enter once
                    //foreach (Employees emp in employees)
                    //{
                    //    e = emp;
                    //}
                    //var logged = new Employee();
                    ////string [] comp = User.Identity.Name.ToLower().Split('.', (char)2, (char)1);
                    ////logged = e.employees.FirstOrDefault(p => p.firstname.ToLower() == comp[0] && p.lastname.ToLower() == comp[1]);
                    //logged = e.employees.FirstOrDefault(p => p.screen_name == username);


                    using (var client = new WebClient())
                    {
                        string data = "{\"screenname\":\"" + username + "\"}";
                        var values = new NameValueCollection();
                        values["screenname"] = username;

                        client.Headers.Add("content-type", "application/json");
                        client.QueryString = values;
                        var responseEmployee = client.UploadData("https://fidelitefunctionapp.azurewebsites.net/api/GetConnectedEmployee", "post", Encoding.Default.GetBytes(data));
                        var responseString = Encoding.Default.GetString(responseEmployee);

                        var firstConv = responseString.Replace("\"", "'");
                        var second = firstConv.Replace("\\", string.Empty);
                        var third = second.Replace("'{", "{");
                        var fourth = third.Replace("}'", "}");
                        var employee = JsonConvert.DeserializeObject<Employee>(fourth);



                        if (ranking == null)
                        {
                            return View("Error");
                        }
                        else
                        {
                            ViewData["ranking"] = ranking;
                            return View(employee);
                        }
                    }
                }
            }
            return View("Error");
        }

        [Authorize(Roles = "Employee")]
        [ActionName("Convert")]
        public ActionResult Convert()
        {
            using (var context = new ApplicationDbContext())
            {
                WebRequest request = WebRequest.Create("https://fidelitefunctionapp.azurewebsites.net/api/GetRewards");
                request.Method = "POST";
                request.ContentType = "application/json";

                Stream dataStream = request.GetRequestStream();
                WebResponse response = request.GetResponse();
                dataStream = response.GetResponseStream();
                StreamReader reader = new StreamReader(dataStream);
                string responseFromServer = reader.ReadToEnd();
                reader.Close();
                dataStream.Close();
                response.Close();

                var first = responseFromServer.Replace("\"", "'");
                var second = first.Replace("\\", string.Empty);
                var third = second.Replace("'[", "[");
                var fourth = third.Replace("]'", "]");
                var rewards = JsonConvert.DeserializeObject<List<Reward>>(fourth);
                ViewData["rewards"] = rewards;

                //   WebRequest request = WebRequest.Create(
                //"https://fidelitefunctionapp.azurewebsites.net/api/GetRewards?code=7LSGHFqUi34TX/7Vq243akHhUKSpdYmC5RqnkEB09D12n/8kfsCNDw==");
                //   // Get the response.  
                //   WebResponse response = request.GetResponse();
                //   // Display the status.  
                //   Console.WriteLine(((HttpWebResponse)response).StatusDescription);
                //   // Get the stream containing content returned by the server.  
                //   Stream dataStream = response.GetResponseStream();
                //   // Open the stream using a StreamReader for easy access.  
                //   StreamReader reader = new StreamReader(dataStream);
                //   // Read the content.  
                //   string responseFromServer = reader.ReadToEnd();
                //   // Display the content.  
                //   Console.WriteLine(responseFromServer);
                //   // Clean up the streams and the response.  
                //   reader.Close();
                //   response.Close();

                //   var first = responseFromServer.Replace("\"", "'");
                //   var second = first.Replace("\\", string.Empty);
                //   var third = second.Replace("'{", "{");
                //   var fourth = third.Replace("}'", "}");
                //   var rewards = JsonConvert.DeserializeObject<Rewards>(fourth);
                //ViewData["rewards"] = rewards;
            }

            var username = User.Identity.Name;
            if (username != null)
            {
                using (var client = new WebClient())
                {
                    string data = "{\"screenname\":\"" + username + "\"}";
                    var values = new NameValueCollection();
                    values["screenname"] = username;
                    client.Headers.Add("content-type", "application/json");
                    client.QueryString = values;
                    var response = client.UploadData("https://fidelitefunctionapp.azurewebsites.net/api/GetConnectedEmployee", "post", Encoding.Default.GetBytes(data));
                    var responseString = Encoding.Default.GetString(response);
                    var first = responseString.Replace("\"", "'");
                    var second = first.Replace("\\", string.Empty);
                    var third = second.Replace("'{", "{");
                    var fourth = third.Replace("}'", "}");
                    var employee = JsonConvert.DeserializeObject<Employee>(fourth);

                    return View(employee);
                }

            }
            return View("Error");
        }


        [ActionName("SendConversion")]
        public ActionResult SendConversion()
        {
            using (var client = new WebClient())
            {
                string username = User.Identity.Name;
                string data = "{\"screenname\":\"" + username + "\"}";
                var values = new NameValueCollection();
                values["screenname"] = username;

                client.Headers.Add("content-type", "application/json");
                client.QueryString = values;
                var response = client.UploadData("https://fidelitefunctionapp.azurewebsites.net/api/GetConnectedEmployee", "post", Encoding.Default.GetBytes(data));
                var responseString = Encoding.Default.GetString(response);

                var first = responseString.Replace("\"", "'");
                var second = first.Replace("\\", string.Empty);
                var third = second.Replace("'{", "{");
                var fourth = third.Replace("}'", "}");
                var employee = JsonConvert.DeserializeObject<Employee>(fourth);

                return View(employee);
            }


            //var request = (HttpWebRequest)WebRequest.Create("https://fidelitefunctionapp.azurewebsites.net/api/GetConnectedEmployee");

            ////var postData = $"screenname=marcnohra";
            ////var data = Encoding.ASCII.GetBytes(postData);
            //byte[] data = Encoding.ASCII.GetBytes("screenname=marcnohra");

            //request.Method = "POST";
            ////request.ContentType = "application/x-www-form-urlencoded";
            //request.ContentType = "application/json";
            ////request.MediaType = "application/xml";
            //request.ContentLength = data.Length;


            //using (var stream = request.GetRequestStream())
            //{
            //    stream.Write(data, 0, data.Length);
            //}

            //var response = (HttpWebResponse)request.GetResponse();

            //var responseString = new StreamReader(response.GetResponseStream()).ReadToEnd();










            //using (var client = new HttpClient())
            //{

ContactManager/ContactManager/Views/Employees/Convert.cshtml
@model ContactManager.Models.Employee
@{
    ViewBag.Title = "Convertir";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var rewards = ViewData["rewards"] as List<ContactManager.Models.Reward>;
}

<h2>Convertir</h2>

<h1>@Model.screen_name Score = @Model.fixScore</h1>





@using (Html.BeginForm("ConvertPoints", "Employees", FormMethod.Post))
{
    <fieldset>
        <div>
            <label for="Rewards">Rewards:</label>
            <select name="Rewards">
                @{
                    foreach (var reward in rewards)
                    {
                        <option value="@reward.name">@reward.name (@reward.points)</option>
                    }
                }
            </select>
        </div>

        <div>
            <label>&nbsp;</label>
            <input type="submit" value="Convert" class="submit" />
        </div>
    </fieldset>
}




@*<form method="post" name="convertPoints">
    <fieldset>
        <div>   
            <label for="Rewards">Rewards:</label>
            <select name="Rewards">
                @{
                    foreach (var reward in rewards)
                    {
                        <option value="@reward.name">@reward.name (@reward.points)</option>
                    }
                }
            </select>
        </div>
        
        <div>
            <label>&nbsp;</label>
            <input type="submit" value="Convert" class="submit" />
        </div>
    </fieldset>
</form>*@

ContactManager/ContactManager/Views/Employees/Create.cshtml
@model ContactManager.Models.Employees

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Employees</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ContactManager/ContactManager/Views/Employees/Edit.cshtml
@model ContactManager.Models.Employees

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Employees</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ContactManager/ContactManager/Views/Employees/Index.cshtml
@model ContactManager.Models.Employee

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var rank = ViewData["ranking"] as List<ContactManager.Models.Rank>;
}

<div class="containe" id="top-converter-div">
    <div style="margin-bottom: 30px;">
        <span class="color-orange bold title">@User.Identity.Name</span>
    </div>
    <div class="container">
        <div class="row">
            <span class="btn col-md-3 no-click orange-bckg color-white">Score Fixe: @Model.fixScore</span>
            <span class="btn col-md-3 col-md-offset-2 no-click orange-bckg color-white">Score Variable: @Model.variableScore</span>
            <br />
        </div>
    </div>
    <br />
    <span>@Html.ActionLink("Convertir", "Convert", "Employees", new { @class = "btn col-md-3 convertir-btn" })</span>
    <br /><br />
    @foreach (var act in Model.activities)
    {
        <br />
        <span>
            @act.platform @act.action = @act.points | date: @act.parentCreatedAt | id: @act.parentId
        </span>
        <br />
    }

    @foreach (var rewards in Model.rewards_used)
    {
        <br />
        <span>
            @rewards.name Date: @rewards.convertDate
        </span>
    }
</div>

<div class="container" id="bottom-converter-div">
    <span class="color-orange bold title">Company's Logs</span>
        @foreach (var act in rank)
        {
            <br />
            <span>
                @act.screen_name Score: @act.variableScore
            </span>
            <br />
        }
</div>

ContactManager/ContactManager/Views/Employees/SendConversion.cshtml
@model ContactManager.Models.Employee

@{
    ViewBag.Title = "SendConversion";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SendConversion</h2>


<h1>@Model.screen_name Score = @Model.fixScore</h1>